"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Download, Menu, X } from "lucide-react";
import { useRole } from "@/context/RoleContext";
import { EngineeringDomain, portfolioIdentity, projects, stackDomains, experiences, verifiedLearning, technologyFlows } from "@/data/portfolioContent";
import { RoleTogglePill } from "@/components/RoleTogglePill";
import { ProjectCaseStudyModal } from "@/components/ProjectCaseStudyModal";
import { CommandPalette } from "@/components/CommandPalette";
import ContactForm from "@/components/ContactForm";
import CustomCursor from "@/components/CustomCursor";
import EngineeringBackground from "@/components/EngineeringBackground";
import HeroWorkbench from "@/components/HeroWorkbench";

const colors: Record<EngineeringDomain,string>={backend:"emerald",ai:"cyan",ml:"violet",data:"teal",infra:"amber"};
export default function Home(){
  const {role,setHoveredDomain,setHoveredTech}=useRole(); const reduced=useReducedMotion();
  const [activeProject,setActiveProject]=useState(0),[detail,setDetail]=useState<typeof projects[number]|null>(null),[domain,setDomain]=useState<EngineeringDomain>("backend"),[techIndex,setTechIndex]=useState(0),[menu,setMenu]=useState(false),[palette,setPalette]=useState(false),[backgroundOpen,setBackgroundOpen]=useState(false);
  const ordered=useMemo(()=>[...projects].sort((a,b)=>a.rolePriority[role==="backendDev"?"backendDev":"dataScience"]-b.rolePriority[role==="backendDev"?"backendDev":"dataScience"]),[role]);
  const stack=stackDomains.find(item=>item.id===domain)!; const tech=stack.technologies[techIndex]||stack.technologies[0]; const flow=technologyFlows[tech.name] || { nodes:[tech.name,tech.role,"Project context"], related:tech.usedIn };
  const activateDomain=(next:EngineeringDomain,index=0)=>{setDomain(next);setTechIndex(index);setHoveredDomain(next==="infra"?"deploy":next);setHoveredTech(stackDomains.find(item=>item.id===next)?.technologies[index]?.name.toLowerCase()||null)};
  const scroll=(id:string)=>document.querySelector(id)?.scrollIntoView({behavior:reduced?"auto":"smooth"});
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  return <main className="meet-site" suppressHydrationWarning><EngineeringBackground/><CustomCursor/>
    <header className="meet-nav"><button className="meet-logo" onClick={()=>scroll("#home")} aria-label="Meet Chhugani home">MC.</button><nav><button onClick={()=>scroll("#work")}>WORK</button><button onClick={()=>scroll("#lab")}>LAB</button><button onClick={()=>scroll("#contact")}>CONTACT</button></nav><div className="meet-nav-actions"><RoleTogglePill/><button className="command-key" onClick={()=>setPalette(true)}>⌘ K</button><a href="/Meet_Chhugani_Resume.pdf" download className="nav-resume">RESUME <Download size={13}/></a><button className="meet-menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button></div></header>
    <AnimatePresence>{menu&&<motion.nav className="meet-mobile-nav" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{[["WORK","#work"],["LAB","#lab"],["CONTACT","#contact"]].map(([label,id])=><button key={id} onClick={()=>{setMenu(false);scroll(id)}}>{label}</button>)}</motion.nav>}</AnimatePresence>
    <HeroWorkbench onExplore={()=>scroll("#work")} onTechnology={activateDomain} onProject={setDetail}/>
    <section id="work" className="work-section-new"><div className="section-heading-new"><p className="micro-label">01 / SELECTED WORK</p><h2>Things I&apos;ve<br/>actually built.</h2><p>Explore a focused set of applications—from modular backend systems to explainable ML and document intelligence.</p></div><div className={`work-rail accent-${colors[ordered[activeProject].domain]}`}>{ordered.map((project,index)=><article key={project.id} onMouseEnter={()=>{setActiveProject(index);activateDomain(project.domain)}} className={`work-project ${activeProject===index?"is-active":""}`}><button data-cursor-label="VIEW PROJECT" onClick={()=>setDetail(project)} className="work-open"><span>{String(index+1).padStart(2,"0")}</span><div><small>{project.tag}</small><h3>{project.title}</h3><p>{project.solution}</p><div className="work-tags">{project.stack.slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="project-art" aria-hidden="true"><b>{project.title.split(" ").slice(0,2).join("\n")}</b><i>{project.metric}</i></div><ArrowUpRight/></button></article>)}</div></section>
    <section id="lab" className="lab-section"><div className="section-heading-new"><p className="micro-label">02 / THE STACK IN ACTION</p><h2>Where the tools<br/>meet the work.</h2><p>Not a list of skills. A look at where I actually use them.</p></div><div className={`stack-action domain-${colors[domain]}`}><aside className="technology-shelf"><p>TECHNOLOGY SHELF</p>{stackDomains.map(item=><button key={item.id} onClick={()=>activateDomain(item.id)} className={domain===item.id?"is-active":""}>{item.label}</button>)}<div className="shelf-technologies">{stack.technologies.map((item,index)=><button key={item.name} onClick={()=>activateDomain(domain,index)} className={techIndex===index?"is-active":""}>{item.name}</button>)}</div></aside><div className="stack-stage"><div className="stage-kicker">HOW I USE IT</div><div className="flow-chain" aria-label={`${tech.name} technology flow`}>{flow.nodes.map((node,index)=><div key={`${tech.name}-${node}`} className={node===tech.name?"flow-node active":"flow-node"}><span>{node}</span>{index<flow.nodes.length-1&&<i/>}</div>)}</div><div className="related-strip"><span>RELATED</span>{flow.related.map(item=><button key={item} onClick={()=>{const i=stack.technologies.findIndex(t=>t.name===item);if(i>=0)activateDomain(domain,i)}}>{item}</button>)}</div><button className="build-stack" onClick={()=>activateDomain(domain,techIndex)}>BUILD WITH THIS <ArrowUpRight size={15}/></button></div><aside className="stack-evidence"><p className="micro-label">PROJECT EVIDENCE</p><h3>{tech.name}</h3><span>{stack.label}</span><dl><div><dt>WHY I USE IT</dt><dd>{tech.why}</dd></div><div><dt>USED IN</dt><dd>{tech.usedIn.join(" · ")}</dd></div><div><dt>ROLE</dt><dd>{tech.role}</dd></div></dl><button onClick={()=>{const p=projects.find(item=>tech.usedIn.includes(item.title));if(p)setDetail(p)}}>VIEW CASE STUDY <ArrowUpRight size={16}/></button><button className="background-toggle" onClick={()=>setBackgroundOpen(!backgroundOpen)} aria-expanded={backgroundOpen}>BACKGROUND {backgroundOpen?"−":"+"}</button>{backgroundOpen&&<div className="background-drawer"><p>{portfolioIdentity.education}</p>{experiences.map(item=><p key={item.role}><b>{item.role}</b><br/>{item.organization}</p>)}<p className="lab-subtitle">VERIFIED LEARNING</p>{verifiedLearning.map(item=><span key={item}>{item}</span>)}</div>}</aside></div></section>
    <section id="contact" className="contact-section-new"><div><p className="micro-label">03 / CONTACT</p><h2>Let&apos;s build<br/>something useful.</h2><p>I&apos;m pursuing software engineering opportunities focused on Python backend development and AI / ML engineering.</p><a href={`mailto:${portfolioIdentity.email}`}>{portfolioIdentity.email}<ArrowUpRight size={16}/></a></div><ContactForm/></section><footer className="meet-footer"><span>© {new Date().getFullYear()} MEET CHHUGANI</span><span>BUILT WITH CURIOSITY &amp; PYTHON</span><div><a href={portfolioIdentity.github}>GITHUB</a><a href={portfolioIdentity.linkedin}>LINKEDIN</a><a href="/Meet_Chhugani_Resume.pdf">RESUME</a></div></footer>
    <ProjectCaseStudyModal project={detail} onClose={()=>setDetail(null)} primaryAccentColor={role==="backendDev"?"text-emerald-300":"text-cyan-300"}/><CommandPalette isOpen={palette} onClose={()=>setPalette(false)}/></main>
}
