"use client";

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight, Download, Code2 as Github, Network as Linkedin, Menu, X } from "lucide-react";
import { EngineeringDomain, portfolioIdentity, projects, stackDomains, technologyFlows } from "@/data/portfolioContent";
import { ProjectCaseStudyModal } from "@/components/ProjectCaseStudyModal";
import { CommandPalette } from "@/components/CommandPalette";
import ContactForm from "@/components/ContactForm";
import CustomCursor from "@/components/CustomCursor";
import EngineeringBackground from "@/components/EngineeringBackground";
import HeroWorkbench from "@/components/HeroWorkbench";
import { useRole } from "@/context/RoleContext";

import BuilderWorkflowSection from "@/components/BuilderWorkflowSection";
import BackgroundSection from "@/components/BackgroundSection";

const colors: Record<EngineeringDomain,string>={backend:"emerald",ai:"cyan",ml:"violet",data:"teal",infra:"amber"};
export default function Home(){
  const {role,setHoveredDomain,setHoveredTech}=useRole(); const reduced=useReducedMotion();
  const [activeProject,setActiveProject]=useState(0),[detail,setDetail]=useState<typeof projects[number]|null>(null),[domain,setDomain]=useState<EngineeringDomain>("backend"),[techIndex,setTechIndex]=useState(0),[menu,setMenu]=useState(false),[palette,setPalette]=useState(false),[scrolled,setScrolled]=useState(false);
  const ordered=useMemo(()=>[...projects].sort((a,b)=>a.rolePriority[role==="backendDev"?"backendDev":"dataScience"]-b.rolePriority[role==="backendDev"?"backendDev":"dataScience"]),[role]);
  const stack=stackDomains.find(item=>item.id===domain)!; const tech=stack.technologies[techIndex]||stack.technologies[0]; const flow=technologyFlows[tech.name] || { nodes:[tech.name,tech.role,"Project context"], related:tech.usedIn };
  const activateDomain=(next:EngineeringDomain,index=0)=>{setDomain(next);setTechIndex(index);setHoveredDomain(next==="infra"?"deploy":next);setHoveredTech(stackDomains.find(item=>item.id===next)?.technologies[index]?.name.toLowerCase()||null)};
  const scroll=(id:string)=>document.querySelector(id)?.scrollIntoView({behavior:reduced?"auto":"smooth"});
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  useEffect(()=>{const update=()=>setScrolled(window.scrollY>18);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update)},[]);
  return <main className="meet-site" suppressHydrationWarning><EngineeringBackground/><CustomCursor/>
    <header className={`meet-nav ${scrolled?"is-scrolled":""}`}><button className="meet-logo" onClick={()=>scroll("#home")} aria-label="Meet Chhugani home">MC.<span>MEET CHHUGANI</span></button><nav><button onClick={()=>scroll("#work")}>WORK</button><button onClick={()=>scroll("#lab")}>LAB</button><button onClick={()=>scroll("#background")}>BACKGROUND</button><button onClick={()=>scroll("#contact")}>CONTACT</button></nav><div className="meet-nav-actions"><a className="nav-profile nav-github" data-cursor-label="OPEN" href={portfolioIdentity.github} target="_blank" rel="noopener noreferrer"><Github size={13}/>GitHub <ArrowUpRight size={11}/></a><a className="nav-profile nav-linkedin" data-cursor-label="OPEN" href={portfolioIdentity.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={13}/>LinkedIn <ArrowUpRight size={11}/></a><a href="/Meet_Chhugani_AI_Engineer_Resume.pdf" download="Meet_Chhugani_AI_Engineer_Resume.pdf" className="nav-resume">RESUME <Download size={13}/></a><button className="meet-menu" onClick={()=>setMenu(!menu)} aria-label="Open navigation">{menu?<X/>:<Menu/>}</button></div></header>
    <AnimatePresence>{menu&&<motion.nav className="meet-mobile-nav" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{[["WORK","#work"],["LAB","#lab"],["BACKGROUND","#background"],["CONTACT","#contact"]].map(([label,id])=><button key={id} onClick={()=>{setMenu(false);scroll(id)}}>{label}</button>)}<a href={portfolioIdentity.github} target="_blank" rel="noopener noreferrer">GITHUB <ArrowUpRight size={12}/></a><a href={portfolioIdentity.linkedin} target="_blank" rel="noopener noreferrer">LINKEDIN <ArrowUpRight size={12}/></a></motion.nav>}</AnimatePresence>
    <HeroWorkbench onExplore={()=>scroll("#work")} onTechnology={activateDomain} onProject={setDetail} isCaseStudyOpen={Boolean(detail)}/>
    <section id="work" className="work-section-new"><motion.div className="section-heading-new work-section-heading" initial={reduced?"visible":"hidden"} whileInView="visible" viewport={{once:true,amount:.3}} variants={{hidden:{},visible:{transition:{staggerChildren:.1}}}}><motion.p className="micro-label" variants={{hidden:{opacity:0,y:14},visible:{opacity:1,y:0,transition:{duration:.5,ease:"easeOut"}}}}>01 / SELECTED WORK</motion.p><motion.h2 variants={{hidden:{opacity:0,y:18},visible:{opacity:1,y:0,transition:{duration:.62,ease:"easeOut"}}}}>Things I&apos;ve<br/><span>Built.</span></motion.h2><motion.p variants={{hidden:{opacity:0,y:14},visible:{opacity:1,y:0,transition:{duration:.55,ease:"easeOut"}}}}>Real systems, experiments, and AI applications I&apos;ve built.</motion.p><motion.i className="work-section-divider" aria-hidden="true" variants={{hidden:{scaleX:0},visible:{scaleX:1,transition:{duration:.8,ease:"easeOut"}}}}/></motion.div><div className={`work-rail accent-${colors[ordered[activeProject].domain]}`}>{ordered.map((project,index)=><article key={project.id} onMouseEnter={()=>{setActiveProject(index);activateDomain(project.domain)}} className={`work-project ${activeProject===index?"is-active":""}`}><button data-cursor-label="VIEW PROJECT" onClick={()=>setDetail(project)} className="work-open"><span>{String(index+1).padStart(2,"0")}</span><div><small>{project.tag}</small><h3>{project.title}</h3><p>{project.solution}</p><div className="work-tags">{project.stack.slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div></div><div className="project-art" aria-hidden="true"><b>{project.title.split(" ").slice(0,2).join("\n")}</b><i>{project.metric}</i></div><ArrowUpRight/></button></article>)}</div></section>
    <section id="lab" className="lab-section"><div className="section-heading-new"><p className="micro-label">02 / HOW I BUILD</p><h2>Tools Behind<br/>the Work.</h2><p>Technologies I use to turn ideas into working backend systems, ML models, and AI applications.</p></div><div className={`stack-action domain-${colors[domain]}`}><aside className="technology-shelf"><p>TECHNOLOGY SHELF</p>{stackDomains.map(item=><button key={item.id} onClick={()=>activateDomain(item.id)} className={domain===item.id?"is-active":""}>{item.label}</button>)}<div className="shelf-technologies">{stack.technologies.map((item,index)=><button key={item.name} onClick={()=>activateDomain(domain,index)} className={techIndex===index?"is-active":""}>{item.name}</button>)}</div></aside><div className="stack-stage"><div className="stage-kicker">HOW I USE IT</div><div className="flow-chain" aria-label={`${tech.name} technology flow`}>{flow.nodes.map((node,index)=><div key={`${tech.name}-${node}`} className={node===tech.name?"flow-node active":"flow-node"}><span>{node}</span>{index<flow.nodes.length-1&&<i/>}</div>)}</div><div className="related-strip"><span>RELATED</span>{flow.related.map(item=><button key={item} onClick={()=>{const i=stack.technologies.findIndex(t=>t.name===item);if(i>=0)activateDomain(domain,i)}}>{item}</button>)}</div><button className="build-stack" onClick={()=>activateDomain(domain,techIndex)}>BUILD WITH THIS <ArrowUpRight size={15}/></button></div><aside className="stack-evidence"><p className="micro-label">PROJECT EVIDENCE</p><h3>{tech.name}</h3><span>{stack.label}</span><dl><div><dt>WHY I USE IT</dt><dd>{tech.why}</dd></div><div><dt>USED IN</dt><dd>{tech.usedIn.join(" · ")}</dd></div><div><dt>ROLE</dt><dd>{tech.role}</dd></div></dl><button onClick={()=>{const p=projects.find(item=>tech.usedIn.includes(item.title));if(p)setDetail(p)}}>VIEW CASE STUDY <ArrowUpRight size={16}/></button></aside></div><BuilderWorkflowSection /></section>
    <BackgroundSection onSelectProject={setDetail} />
    <section id="contact" className="contact-section-new"><div><p className="micro-label">04 / CONTACT</p><h2>Let&apos;s Build<br/>Something.</h2><p>If you&apos;re working on a Python backend, ML system, or AI application and think I could contribute, I&apos;d like to hear about it.</p><a href={`mailto:${portfolioIdentity.email}`}>{portfolioIdentity.email}<ArrowUpRight size={16}/></a></div><ContactForm/></section><footer className="meet-footer"><span>© 2026 MEET CHHUGANI</span><span>AI / ML ENGINEER · PYTHON BACKEND DEVELOPER</span><div><a href={portfolioIdentity.github}>GITHUB</a><a href={portfolioIdentity.linkedin}>LINKEDIN</a><a href={`mailto:${portfolioIdentity.email}`}>EMAIL</a><a href="/Meet_Chhugani_AI_Engineer_Resume.pdf" download="Meet_Chhugani_AI_Engineer_Resume.pdf">RESUME</a></div></footer>
    <ProjectCaseStudyModal project={detail} onClose={()=>setDetail(null)} primaryAccentColor={role==="backendDev"?"text-emerald-300":"text-cyan-300"}/><CommandPalette isOpen={palette} onClose={()=>setPalette(false)}/></main>
}
